#!/bin/sh

# Little Things
#  _________________________________________________________________________________________        
#   _________________________________________________________________________________________       
#    ______________________/\\\________________/\\\_____/\\\__________________________________      
#     ________/\\\____/\\\_\///___/\\/\\\\\\___\///___/\\\\\\\\\\\__/\\/\\\\\\\______/\\\\\\\\_     
#      _______\///\\\/\\\/___/\\\_\/\\\////\\\___/\\\_\////\\\////__\/\\\/////\\\___/\\\//////__    
#       _________\///\\\/____\/\\\_\/\\\__\//\\\_\/\\\____\/\\\______\/\\\___\///___/\\\_________   
#        __________/\\\/\\\___\/\\\_\/\\\___\/\\\_\/\\\____\/\\\_/\\__\/\\\_________\//\\\________  
#         __/\\\__/\\\/\///\\\_\/\\\_\/\\\___\/\\\_\/\\\____\//\\\\\___\/\\\__________\///\\\\\\\\_ 
#          _\///__\///____\///__\///__\///____\///__\///______\/////____\///_____________\////////__

userresources=$XDG_CONFIG_HOME/X11/Xresources
usermodmap=$XDG_CONFIG_HOME/X11/Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

xscreensaver &
mpd &
exec i3
